### ISSUE TITLE
Gettign an Operational Error upon login

### ISSUE THREAD

**Issue by mtastafford** [coogger/steemconnect_auth#1]
trying to create a new steemconnectuser throws an operational error:

```
ser.save()
Traceback (most recent call last):
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: steemconnect_auth_steemconnectuser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/models/base.py", line 717, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/models/base.py", line 747, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/models/base.py", line 830, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/models/base.py", line 868, in _do_insert
    using=using, raw=raw)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1133, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/xhauststaging/xhaust/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: steemconnect_auth_steemconnectuser
```

**Comment by hakancelikdev** [comment]
Try these code for db migration in your django app
```python
python manage.py makemigrations steemconnect_auth
python manage.py migrate
```

- EDİT -

**Comment by hakancelikdev** [comment]
and you should update using this code

```
pip install steemconnect_auth -U
```

**Comment by mtastafford** [comment]
ahh of course!
```
python manage.py makemigrations steemconnect_auth
```
and;
```
pip install --upgrade steemconnect_auth
```

cleared this all up for me. Thanks!
